" ************Vundle and Packages***************

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'rakr/vim-one'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" ***** THEME AND HIGHLIGHTING ******

" syntax highlighting
syntax on

" this print formatting chars are required for vim-one
set t_8b=[48;2;%lu;%lu;%lum
set t_8f=[38;2;%lu;%lu;%lum
" get those nice colors
"set termguicolors
" italics
let g:one_allow_italics = 1
" sets the dark theme
set background=dark
" set the color scheme
colorscheme one
" colorscheme OceanicNext
" colorscheme seoul256
" colorscheme neuromancer
" colorscheme badwolf
" colorscheme vice
" set vim-airline theme to also use the 'vim-one' styles
let g:airline_theme='one'
